### ISSUE TITLE
sbt crash

### ISSUE THREAD

**Issue by rwst** [weso/shaclex#350]
When on master running sbt in the directory I get
```
Exception in thread "sbt-parser-init-thread" java.lang.NoSuchMethodError: scala.Some.value()Ljava/lang/Object;
	at sbt.io.IO$.uriToFile(IO.scala:258)
	at sbt.io.IO$.toFile(IO.scala:228)
	at sbt.io.IO$.classLocationPath(IO.scala:68)
	at sbt.io.IO$.classLocationPath(IO.scala:82)
	at sbt.internal.parser.SbtParser$.<init>(SbtParser.scala:45)
	at sbt.internal.parser.SbtParser$.<clinit>(SbtParser.scala)
	at sbt.internal.parser.SbtParserInit$$anon$2.run(SbtParser.scala:171)
java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at sbt.internal.util.Prompt$Batch$.<init>(Prompt.scala:35)
	at sbt.internal.util.Prompt$Batch$.<clinit>(Prompt.scala)
	at sbt.internal.util.Terminal.$init$(Terminal.scala:156)
	at sbt.internal.util.Terminal$DefaultTerminal.<init>(Terminal.scala:945)
	at sbt.internal.util.Terminal$SimpleTerminal$.<init>(Terminal.scala:978)
	at sbt.internal.util.Terminal$SimpleTerminal$.<clinit>(Terminal.scala)
	at sbt.internal.util.Terminal$.<init>(Terminal.scala:553)
	at sbt.internal.util.Terminal$.<clinit>(Terminal.scala)
	at sbt.xMain$.run(Main.scala:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
```
`git bisect` tells me that this started with commit 37400678028f8c67d. When checking out the commit before that, i.e. 7c09a4e1398f941533 `sbt test` compiles and tests fine.

Please fix!

**Comment by labra** [comment]
Thanks for the report. What version of sbt do you have? I am asking because it works in my computer and it could a problem with the version of sbt, could you check which version of sbt you are using?

**Comment by rwst** [comment]
When I go back to the working commit then this gets installed: `sbt 1.3.13 (IcedTea Java 1.8.0_252)`
When I create an empty dir and start sbt: `sbt 1.4.2 (IcedTea Java 1.8.0_252)`

**Comment by rwst** [comment]
FWIW I get the same crash if I change the java to version 11.

**Comment by rwst** [comment]
And the same with `sbt 1.4.2 (Oracle Corporation Java 1.8.0_162)`.

**Comment by rwst** [comment]
OK. It works when I change project/build.properties to `sbt.version=1.4.2`.

**Comment by labra** [comment]
Ah!, great that it works now!, 

I may had forgotten to commit that part. Do you want to do a pull request with that change?

**Comment by labra** [comment]
I noticed you had already done it :smile:, thanks!
